export enum UserStatus
{
    WAITING_EMAIL_VERIFICATION = 'WAITING_EMAIL_VERIFICATION',
    ACTIVE = 'ACTIVE',
    FREE_TRIAL_PERIOD = 'FREE_TRIAL_PERIOD',
    FREE_TRIAL_PERIOD_EXPIRED = 'FREE_TRIAL_PERIOD_EXPIRED',
    SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',
    SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED',
    WAITING_FOR_PAYMENT = 'WAITING_FOR_PAYMENT',
    BLOCKED = 'BLOCKED'
}